### ISSUE TITLE
BUG: Connection to node with disablewallet option not possible.

### ISSUE THREAD

**Issue by MarkusNeusinger** [eric-volz/DefichainPython#116]
**Describe the bug**
It is not possible to connect to a node without a wallet.

**To Reproduce**
Run node with disablewallet=1 in defi.conf
node =  Node("user", "pw", url="node.defichain-data.com", port=8555)
-> defichain.exceptions.http.NotFound.NotFound: NotFound(404): RPC_METHOD_NOT_FOUND: Method not found

**Expected behavior**
It should be possible to connect, with a wallet needing functionality disabled.

**Additional context**
I want to run a free access node for data analysis tasks and for security reasons have the wallet functionality disabled.

**Comment by eric-volz** [comment]
Thank you for letting me know and creating the issue. I will look into it in the next days!👍🏻

**Comment by eric-volz** [comment]
There is now an argument in the node object class that allows you to disable the wallet functionality inside the node: `disablewallet = True`

**Comment by MarkusNeusinger** [comment]
That was fast, thank you, looking forward to using it with disabled wallet.
