### ISSUE TITLE
Please Add a Simple Example of sending DFI between accounts

### ISSUE THREAD

**Issue by Web3isFuture** [eric-volz/DefichainPython#65]
Hello,

As I have seen the full project I am unable to find a fully working example of Sending token from one wallet to another.

it can help new people as it is a common transaction of transferring tokens .

**Comment by eric-volz** [comment]
Hey,

there is a [Quickstart Guide](https://docs.defichain-python.de/build/html/instructions/quickstart.html) where you can view a working example of two also very commonly used methods.
If you want to send tokens from one account to another, you just have to use other methods.

To send UTXO you can use the method: [**sendutxosfrom**](https://docs.defichain-python.de/build/html/api/node/accounts.html#defichain.node.Accounts.sendutxosfrom)
To send tokens you can use the method: [**sendtokenstoaddress**](https://docs.defichain-python.de/build/html/api/node/accounts.html#defichain.node.Accounts.sendtokenstoaddress)

Every method in the documentation also has an example how to use the individual method. You just have to have to replace this example with the methods specified in the Quickstart Guide and it should be working.

I hope this has helped you. Feel free to let me know if you need any further assistance. :)

**Comment by Web3isFuture** [comment]
thank you eric for your time,
one more question will you be adding a way to generate hexstring for ocean rawTx send function?

**Comment by eric-volz** [comment]
**Your welcome :)**

I'm already on it. :) You can see the progress in the [raw_transaction](https://github.com/eric-volz/DefichainPython/tree/raw_transactions) branch. 
My time is very limited right now, so it will take a while until it is finished. 
When it's ready, I'll announce it on Reddit!
