### ISSUE TITLE
Build Status Page on Notion

### ISSUE THREAD

**Issue by eric-volz** [eric-volz/DefichainPython#95]
# Description:

Give a basic overview of what is already finished, in progress, outdated or not jet implemented.
This information will be displayed on an embedded [notion page](https://defichain-python.notion.site/Status-4f795cdca247446ea2b08e6467afd204?pvs=4).

## Things to do:

- [x] Embed page into documentation
- [x] Build main page
- [x] Build Node / RPC page
- [x] Build Ocean page
- [x] Build HDWallet page
- [x] Build Transactions page

**Comment by 0ptim** [comment]
Maybe link to the notion page from main README?

**Comment by eric-volz** [comment]
Good idea, thanks!

- [ ] Link to status page on README
